update ramdisc

diff --git a/misc/ramdisk b/misc/ramdisk
--- a/misc/ramdisk
+++ b/misc/ramdisk
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -e
 
+if [[ "0" == `id -u` ]]; then
+  echo "ERROR do not run this as root"
+  exit 1
+fi
+
 if [[ ! -z `mount | fgrep /mnt/ramdisk` ]]; then
   mount | fgrep /mnt/ramdisk
   exit 	
